server {
    listen 80;
    server_name inflowcan.net;

    # We'll redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

 server {
    listen 443 ssl;
    server_name inflowcan.net;
    ssl_certificate /etc/letsencrypt/live/inflowcan.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/inflowcan.net/privkey.pem; # managed by Certbot


    # SSL certificates will be added by certbot

    # Camera permission policies
    add_header Feature-Policy "camera 'self'";
    add_header Permissions-Policy "camera=self";

    # Frontend proxy
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

  location /api/ {
    proxy_pass http://csharp-backend:5001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}



    # Increase request size limit for image uploads
    client_max_body_size 10M;

}
~                                     